# -*- mode: python; tab-width: 4; indent-tabs-mode: nil -*-

from djdardos.dardos.models import *
from django import forms
import datetime

class PartidoPreForm(forms.Form):
    #jornada = models.ForeignKey(Jornada)
    fecha = forms.DateField(input_formats=('%d-%m-%Y', '%d/%m/%Y'))
    jornada = forms.ModelChoiceField(queryset=Jornada.objects.filter(partido=None))
    equipo_local = forms.ModelChoiceField(queryset=Equipo.objects.all().order_by("nombre"))
    equipo_visitante = forms.ModelChoiceField(queryset=Equipo.objects.all().order_by("nombre"))
    
    def clean(self):
        cleaned_data = self.cleaned_data
        #TODO Comprobar que no hayan jugado ya
        if (cleaned_data['equipo_local'].id == cleaned_data['equipo_visitante'].id):
            raise forms.ValidationError("No puedes seleccionar el mismo equipo")
        return cleaned_data


class PartidoForm(forms.Form):
    
    equipo_local = forms.IntegerField()
    equipo_visitante = forms.IntegerField()
    
    par501jl1_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jl2_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jv1_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jv2_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501g_1 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    par501jl1_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jl2_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jv1_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jv2_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501g_2 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    par501jl1_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jl2_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jv1_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jv2_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501g_3 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    par501jl1_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jl2_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jv1_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501jv2_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    par501g_4 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    
    ind501jl1_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501jv1_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501g_1 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    ind501jl1_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501jv1_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501g_2 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    ind501jl1_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501jv1_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501g_3 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    ind501jl1_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501jv1_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501g_4 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    
    parcrijl1_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijl2_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijv1_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijv2_1 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrig_1 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    parcrijl1_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijl2_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijv1_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijv2_2 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrig_2 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    parcrijl1_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijl2_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijv1_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijv2_3 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrig_3 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    parcrijl1_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijl2_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijv1_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrijv2_4 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    parcrig_4 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    
    ind501jl1_5 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501jv1_5 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501g_5 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    ind501jl1_6 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501jv1_6 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501g_6 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    ind501jl1_7 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501jv1_7 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501g_7 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    ind501jl1_8 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501jv1_8 = forms.ModelChoiceField(queryset=Jugador.objects.none())
    ind501g_8 = forms.ModelChoiceField(queryset=Equipo.objects.none())
    
    def cargar_datos_por_id(self, id_local, id_visitante):
        self.cargar_datos(Equipo.objects.get(pk=id_local), Equipo.objects.get(pk=id_visitante))
        
    def cargar_datos(self, equipo_local, equipo_visitante):
        self.fields['equipo_local'].initial = equipo_local.id
        self.fields['equipo_visitante'].initial = equipo_visitante.id
        self.fields['par501jl1_1'].queryset = equipo_local.jugador_set.all()
        self.fields['par501jl2_1'].queryset = equipo_local.jugador_set.all()
        self.fields['par501jv1_1'].queryset = equipo_visitante.jugador_set.all()
        self.fields['par501jv2_1'].queryset = equipo_visitante.jugador_set.all()
        self.fields['par501g_1'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['par501jl1_2'].queryset = equipo_local.jugador_set.all()
        self.fields['par501jl2_2'].queryset = equipo_local.jugador_set.all()
        self.fields['par501jv1_2'].queryset = equipo_visitante.jugador_set.all()
        self.fields['par501jv2_2'].queryset = equipo_visitante.jugador_set.all()
        self.fields['par501g_2'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['par501jl1_3'].queryset = equipo_local.jugador_set.all()
        self.fields['par501jl2_3'].queryset = equipo_local.jugador_set.all()
        self.fields['par501jv1_3'].queryset = equipo_visitante.jugador_set.all()
        self.fields['par501jv2_3'].queryset = equipo_visitante.jugador_set.all()
        self.fields['par501g_3'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['par501jl1_4'].queryset = equipo_local.jugador_set.all()
        self.fields['par501jl2_4'].queryset = equipo_local.jugador_set.all()
        self.fields['par501jv1_4'].queryset = equipo_visitante.jugador_set.all()
        self.fields['par501jv2_4'].queryset = equipo_visitante.jugador_set.all()
        self.fields['par501g_4'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        
        self.fields['ind501jl1_1'].queryset = equipo_local.jugador_set.all()
        self.fields['ind501jv1_1'].queryset = equipo_visitante.jugador_set.all()
        self.fields['ind501g_1'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['ind501jl1_2'].queryset = equipo_local.jugador_set.all()
        self.fields['ind501jv1_2'].queryset = equipo_visitante.jugador_set.all()
        self.fields['ind501g_2'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['ind501jl1_3'].queryset = equipo_local.jugador_set.all()
        self.fields['ind501jv1_3'].queryset = equipo_visitante.jugador_set.all()
        self.fields['ind501g_3'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['ind501jl1_4'].queryset = equipo_local.jugador_set.all()
        self.fields['ind501jv1_4'].queryset = equipo_visitante.jugador_set.all()
        self.fields['ind501g_4'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        
        self.fields['parcrijl1_1'].queryset = equipo_local.jugador_set.all()
        self.fields['parcrijl2_1'].queryset = equipo_local.jugador_set.all()
        self.fields['parcrijv1_1'].queryset = equipo_visitante.jugador_set.all()
        self.fields['parcrijv2_1'].queryset = equipo_visitante.jugador_set.all()
        self.fields['parcrig_1'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['parcrijl1_2'].queryset = equipo_local.jugador_set.all()
        self.fields['parcrijl2_2'].queryset = equipo_local.jugador_set.all()
        self.fields['parcrijv1_2'].queryset = equipo_visitante.jugador_set.all()
        self.fields['parcrijv2_2'].queryset = equipo_visitante.jugador_set.all()
        self.fields['parcrig_2'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['parcrijl1_3'].queryset = equipo_local.jugador_set.all()
        self.fields['parcrijl2_3'].queryset = equipo_local.jugador_set.all()
        self.fields['parcrijv1_3'].queryset = equipo_visitante.jugador_set.all()
        self.fields['parcrijv2_3'].queryset = equipo_visitante.jugador_set.all()
        self.fields['parcrig_3'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['parcrijl1_4'].queryset = equipo_local.jugador_set.all()
        self.fields['parcrijl2_4'].queryset = equipo_local.jugador_set.all()
        self.fields['parcrijv1_4'].queryset = equipo_visitante.jugador_set.all()
        self.fields['parcrijv2_4'].queryset = equipo_visitante.jugador_set.all()
        self.fields['parcrig_4'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        
        self.fields['ind501jl1_5'].queryset = equipo_local.jugador_set.all()
        self.fields['ind501jv1_5'].queryset = equipo_visitante.jugador_set.all()
        self.fields['ind501g_5'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['ind501jl1_6'].queryset = equipo_local.jugador_set.all()
        self.fields['ind501jv1_6'].queryset = equipo_visitante.jugador_set.all()
        self.fields['ind501g_6'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['ind501jl1_7'].queryset = equipo_local.jugador_set.all()
        self.fields['ind501jv1_7'].queryset = equipo_visitante.jugador_set.all()
        self.fields['ind501g_7'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        self.fields['ind501jl1_8'].queryset = equipo_local.jugador_set.all()
        self.fields['ind501jv1_8'].queryset = equipo_visitante.jugador_set.all()
        self.fields['ind501g_8'].queryset = Equipo.objects.filter(pk__in=[equipo_local.id, equipo_visitante.id])
        
