from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

urlpatterns = patterns('djdardos.dardos.views',
    url(r'^ligas/$',    'ligas.ligas_index',    name='dardos-ligas-index'),
    url(r'^login/$',    'general.login',        name='dardos-general-login'),
    url(r'^logout/$',   'general.logout',       name='dardos-general-logout'),
    url(r'^error_permisos/$',direct_to_template, {
        'template': 'dardos/general/error_permisos.html'},
        name='dardos-general-error-permisos'),
    url(r'^cambiar_liga/$', 'general.cambiar_liga',
        name='dardos-general-cambiar_liga'),
    url(r'^equipos/$', 'equipos.index', name='dardos-equipos-index'),
    url(r'^equipos/estreport/(?P<equipo_id>\d+)/(?P<liga_id>\d+)$',
        'equipos.estreport', name='dardos-equipos-estreport'),
    url(r'^equipos/estparejas/(?P<equipo_id>\d+)/(?P<liga_id>\d+)$',
        'equipos.ajax_estadistica_parejas', name='dardos-equipos-estparejas'),
    url(r'^equipos/(?P<equipo_id>\d+)/$', 'equipos.detail', 
        name='dardos-equipos-detail'),
    url(r'^jugadores/$', 'jugadores.index', name='dardos-jugadores-index'),
    url(r'^jugadores/(?P<jugador_id>\d+)/$', 'jugadores.detail',
        name='dardos-jugadores-detail'),
    url(r'^partidos/$', 'partidos.index', name='dardos-partidos-index'),
    url(r'^partidos/(?P<partido_id>\d+)/(?P<reporting>\w+)/$',
        'partidos.detail', name='dardos-partidos-detail-reporting'),
    url(r'^partidos/(?P<partido_id>\d+)/$', 'partidos.detail',
        name='dardos-partidos-detail'),
    url(r'^partidos/new/$', 'partidos.new', name='dardos-partidos-new'),
    url(r'^partidos/partidas/(?P<partido_id>\d+)/$', 'partidos.setpartidas',
        name='dardos-partidos-setpartidas'),
    url(r'^partidos/new_jornada/$', 'partidos.new_jornada',
        name='dardos-partidos-new_jornada'),
    url(r'^liga/(?P<liga_id>\d+)/ajax_get_siguiente_jornada/$',
        'partidos.ajax_get_siguiente_jornada',
        name='dardos-partidos-ajax_get_siguiente_jornada'),
    url(r'^division/(?P<division_id>\d+)/$', 'divisiones.detail',
        name='dardos-divisiones-detail'),
    url(r'^ajax_jornada_detail/(?P<jornada_id>\d+)/$', 
        'divisiones.ajax_jornada_detail', 
        name='dardos-divisiones-ajax_jornada_detail'),
    url(r'^ajax_grafica_evolucion/$', 'graficas.ajax_grafica_evolucion',
        name='dardos-graficas-ajax_grafica_evolucion'),
    url(r'^maestros/ajax_jornadas_from_liga/(?P<liga_id>\d+)/$',
        'maestros.ajax_jornadas_from_liga',
        name='dardos-maestros-ajax_jornadas_from_liga'),
    url(r'^maestros/ajax_equipos_from_liga/(?P<liga_id>\d+)/$',
        'maestros.ajax_equipos_from_liga',
        name='dardos-maestros-ajax_equipos_from_liga'),
)
